### ISSUE TITLE
Manifest for reactioncommerce/identity:local-dev not found

### ISSUE THREAD

**Issue by trojanh** [reactioncommerce/reaction-identity#20]
When running `make` command with below steps 
```
$ cd reaction-identity 
$ ln -sf docker-compose.dev.yml docker-compose.override.yml
$ cd ..
$ make stop-reaction-identity 
$ make start-reaction-identity 
```
I get following error 
```
Pulling identity ... error

ERROR: for identity  manifest for reactioncommerce/identity:local-dev not found: manifest unknown: manifest unknown
ERROR: manifest for reactioncommerce/identity:local-dev not found: manifest unknown: manifest unknown
reaction-identity_identity_1 is up-to-date
```

running `reaction-platform@release-v3.0.0`

**Comment by aldeed** [comment]
@trojanh Does this cause any problems? I'm aware of an error similar to this being printed when you `make` with the override in place, but I'm pretty sure everything still works. It's just the `docker-compose pull` that fails, which as far as I can tell is a bug with that command. We are using the `image` to mean "desired image name", but it's interpreting it as something to be pulled.

https://github.com/reactioncommerce/reaction-development-platform/blob/trunk/Makefile#L284-L287

**Comment by trojanh** [comment]
yeah, it works @aldeed  but just wanted to log the error message here.

**Comment by aldeed** [comment]
Closing this because I can't think of any solution within Reaction. There needs to be some "pull only if there isn't a `build`" option for the `docker-compose pull` command, and there currently isn't.
