### ISSUE TITLE
Remove hard dependencies on Reaction API

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-identity#29]
Related to #16 

We did not quite get this to the point of being usable outside of Reaction prior to the 3.0.0 release. Currently it needs the Reaction API for sending emails. This issue is an enhancement request to abstract the email sending such that this does not require the Reaction API to work. At that point it will not be specific to Reaction and could be named `meteor-identity` or `meteor-oauth-identity` to reflect this.

**Comment by delagroove** [comment]
dropping ahead of 4.0 release
